import { ReactNode } from 'react'
import {
    FcAbout,
    FcAcceptDatabase,
    FcAddColumn,
    FcAddDatabase,
    FcAddImage,
    FcAddRow,
    FcAddressBook,
    FcAdvance,
    FcAdvertising,
    FcAlarmClock,
    FcAlphabeticalSortingAz,
    FcAlphabeticalSortingZa,
    FcAndroidOs,
    FcAnswers,
    FcApproval,
    FcApprove,
    FcAreaChart,
    FcAssistant,
    FcAudioFile,
    FcAutomatic,
    FcAutomotive,
    FcBadDecision,
    FcBarChart,
    FcBbc,
    FcBearish,
    FcBinoculars,
    FcBiohazard,
    FcBiomass,
    FcBiotech,
    FcBookmark,
    FcBriefcase,
    FcBrokenLink,
    FcBullish,
    FcBusiness,
    FcBusinessContact,
    FcBusinessman,
    FcBusinesswoman,
    FcButtingIn,
    FcCableRelease,
    FcCalculator,
    FcCalendar,
    FcCallTransfer,
    FcCallback,
    FcCamcorder,
    FcCamcorderPro,
    FcCamera,
    FcCameraAddon,
    FcCameraIdentification,
    FcCancel,
    FcCandleSticks,
    FcCapacitor,
    FcCdLogo,
    FcCellPhone,
    FcChargeBattery,
    FcCheckmark,
    FcCircuit,
    FcClapperboard,
    FcClearFilters,
    FcClock,
    FcCloseUpMode,
    FcCloth,
    FcCollaboration,
    FcCollapse,
    FcCollect,
    FcComboChart,
    FcCommandLine,
    FcComments,
    FcCompactCamera,
    FcConferenceCall,
    FcContacts,
    FcCopyleft,
    FcCopyright,
    FcCrystalOscillator,
    FcCurrencyExchange,
    FcCursor,
    FcCustomerSupport,
    FcDam,
    FcDataBackup,
    FcDataConfiguration,
    FcDataEncryption,
    FcDataProtection,
    FcDataRecovery,
    FcDataSheet,
    FcDatabase,
    FcDebian,
    FcDebt,
    FcDecision,
    FcDeleteColumn,
    FcDeleteDatabase,
    FcDeleteRow,
    FcDepartment,
    FcDeployment,
    FcDiploma1,
    FcDiploma2,
    FcDisapprove,
    FcDisclaimer,
    FcDislike,
    FcDisplay,
    FcDoNotInhale,
    FcDoNotInsert,
    FcDoNotMix,
    FcDocument,
    FcDonate,
    FcDoughnutChart,
    FcDown,
    FcDownLeft,
    FcDownRight,
    FcDownload,
    FcDribbble,
    FcDvdLogo,
    FcEditImage,
    FcElectricalSensor,
    FcElectricalThreshold,
    FcElectricity,
    FcElectroDevices,
    FcElectronics,
    FcEmptyBattery,
    FcEmptyFilter,
    FcEmptyTrash,
    FcEndCall,
    FcEngineering,
    FcEnteringHeavenAlive,
    FcExpand,
    FcExpired,
    FcExport,
    FcExternal,
    FcFactory,
    FcFactoryBreakdown,
    FcFaq,
    FcFeedIn,
    FcFeedback,
    FcFile,
    FcFilingCabinet,
    FcFilledFilter,
    FcFilm,
    FcFilmReel,
    FcFinePrint,
    FcFlashAuto,
    FcFlashOff,
    FcFlashOn,
    FcFlowChart,
    FcFolder,
    FcFrame,
    FcFullBattery,
    FcFullTrash,
    FcGallery,
    FcGenealogy,
    FcGenericSortingAsc,
    FcGenericSortingDesc,
    FcGlobe,
    FcGoodDecision,
    FcGoogle,
    FcGraduationCap,
    FcGrid,
    FcHeadset,
    FcHeatMap,
    FcHighBattery,
    FcHighPriority,
    FcHome,
    FcIcons8Cup,
    FcIdea,
    FcImageFile,
    FcImport,
    FcInTransit,
    FcInfo,
    FcInspection,
    FcIntegratedWebcam,
    FcInternal,
    FcInvite,
    FcIpad,
    FcIphone,
    FcKey,
    FcKindle,
    FcLandscape,
    FcLeave,
    FcLeft,
    FcLeftDown,
    FcLeftDown2,
    FcLeftUp,
    FcLeftUp2,
    FcLibrary,
    FcLightAtTheEndOfTunnel,
    FcLike,
    FcLikePlaceholder,
    FcLineChart,
    FcLink,
    FcLinux,
    FcList,
    FcLock,
    FcLockLandscape,
    FcLockPortrait,
    FcLowBattery,
    FcLowPriority,
    FcMakeDecision,
    FcManager,
    FcMediumPriority,
    FcMenu,
    FcMindMap,
    FcMinus,
    FcMissedCall,
    FcMms,
    FcMoneyTransfer,
    FcMultipleCameras,
    FcMultipleDevices,
    FcMultipleInputs,
    FcMultipleSmartphones,
    FcMusic,
    FcNegativeDynamic,
    FcNeutralDecision,
    FcNeutralTrading,
    FcNews,
    FcNext,
    FcNfcSign,
    FcNightLandscape,
    FcNightPortrait,
    FcNoIdea,
    FcNoVideo,
    FcNook,
    FcNumericalSorting12,
    FcNumericalSorting21,
    FcOk,
    FcOldTimeCamera,
    FcOnlineSupport,
    FcOpenedFolder,
    FcOrgUnit,
    FcOrganization,
    FcOvertime,
    FcPackage,
    FcPaid,
    FcPanorama,
    FcParallelTasks,
    FcPhone,
    FcPhoneAndroid,
    FcPhotoReel,
    FcPicture,
    FcPieChart,
    FcPlanner,
    FcPlus,
    FcPodiumWithAudience,
    FcPodiumWithSpeaker,
    FcPodiumWithoutSpeaker,
    FcPortraitMode,
    FcPositiveDynamic,
    FcPrevious,
    FcPrint,
    FcPrivacy,
    FcProcess,
    FcPuzzle,
    FcQuestions,
    FcRadarPlot,
    FcRating,
    FcRatings,
    FcReading,
    FcReadingEbook,
    FcReddit,
    FcRedo,
    FcRefresh,
    FcRegisteredTrademark,
    FcRemoveImage,
    FcReuse,
    FcRight,
    FcRightDown,
    FcRightDown2,
    FcRightUp,
    FcRightUp2,
    FcRotateCamera,
    FcRotateToLandscape,
    FcRotateToPortrait,
    FcRuler,
    FcRules,
    FcSafe,
    FcSalesPerformance,
    FcScatterPlot,
    FcSearch,
    FcSelfServiceKiosk,
    FcSelfie,
    FcSerialTasks,
    FcServiceMark,
    FcServices,
    FcSettings,
    FcShare,
    FcShipped,
    FcShop,
    FcSignature,
    FcSimCard,
    FcSimCardChip,
    FcSlrBackSide,
    FcSmartphoneTablet,
    FcSms,
    FcSoundRecordingCopyright,
    FcSpeaker,
    FcSportsMode,
    FcStackOfPhotos,
    FcStart,
    FcStatistics,
    FcSteam,
    FcStumbleupon,
    FcSupport,
    FcSurvey,
    FcSwitchCamera,
    FcSynchronize,
    FcTabletAndroid,
    FcTemplate,
    FcTimeline,
    FcTodoList,
    FcTouchscreenSmartphone,
    FcTrademark,
    FcTreeStructure,
    FcTwoSmartphones,
    FcUndo,
    FcUnlock,
    FcUp,
    FcUpLeft,
    FcUpRight,
    FcUpload,
    FcUsb,
    FcVideoCall,
    FcVideoFile,
    FcVideoProjector,
    FcViewDetails,
    FcVip,
    FcVlc,
    FcVoicePresentation,
    FcVoicemail,
    FcWebcam,
    FcWiFiLogo,
    FcWikipedia,
    FcWorkflow,
} from 'react-icons/fc'

import {
    CiAirportSign1,
    CiAlarmOff,
    CiAlarmOn,
    CiAlignBottom,
    CiAlignCenterH,
    CiAlignCenterV,
    CiAlignLeft,
    CiAlignRight,
    CiAlignTop,
    CiApple,
    CiAt,
    CiAvocado,
    CiBacon,
    CiBadgeDollar,
    CiBag1,
    CiBandage,
    CiBank,
    CiBarcode,
    CiBaseball,
    CiBasketball,
    CiBatteryCharging,
    CiBatteryEmpty,
    CiBatteryFull,
    CiBeaker1,
    CiBeerMugFull,
    CiBellOff,
    CiBellOn,
    CiBezier,
    CiBitcoin,
    CiBluetooth,
    CiBookmark,
    CiBookmarkCheck,
    CiBookmarkMinus,
    CiBookmarkPlus,
    CiBookmarkRemove,
    CiBowlNoodles,
    CiBoxList,
    CiBoxes,
    CiBrightnessDown,
    CiBrightnessUp,
    CiBullhorn,
    CiBurger,
    CiCalculator1,
    CiCalculator2,
    CiCalendar,
    CiCalendarDate,
    CiCamera,
    CiChat1,
    CiChat2,
    CiCircleAlert,
    CiCircleCheck,
    CiCircleChevDown,
    CiCircleChevLeft,
    CiCircleChevRight,
    CiCircleChevUp,
    CiCircleInfo,
    CiCircleList,
    CiCircleMinus,
    CiCircleMore,
    CiCirclePlus,
    CiCircleQuestion,
    CiCircleRemove,
    CiClock1,
    CiClock2,
    CiCloud,
    CiCloudDrizzle,
    CiCloudMoon,
    CiCloudOff,
    CiCloudOn,
    CiCloudRainbow,
    CiCloudSun,
    CiCoffeeBean,
    CiCoffeeCup,
    CiCoinInsert,
    CiCoins1,
    CiCompass1,
    CiCreditCard1,
    CiCreditCard2,
    CiCreditCardOff,
    CiCrop,
    CiDark,
    CiDatabase,
    CiDeliveryTruck,
    CiDesktop,
    CiDesktopMouse1,
    CiDesktopMouse2,
    CiDiscount1,
    CiDollar,
    CiDroplet,
    CiDumbbell,
    CiEdit,
    CiEraser,
    CiExport,
    CiFaceFrown,
    CiFaceMeh,
    CiFaceSmile,
    CiFacebook,
    CiFileOff,
    CiFileOn,
    CiFilter,
    CiFlag1,
    CiFloppyDisk,
    CiFolderOff,
    CiFolderOn,
    CiFootball,
    CiForkAndKnife,
    CiFries,
    CiGift,
    CiGlass,
    CiGlobe,
    CiGps,
    CiGrid2H,
    CiGrid2V,
    CiGrid31,
    CiGrid32,
    CiGrid41,
    CiGrid42,
    CiHardDrive,
    CiHashtag,
    CiHeadphones,
    CiHeart,
    CiHome,
    CiHospital1,
    CiHotdog,
    CiIceCream,
    CiImageOff,
    CiImageOn,
    CiImport,
    CiInboxIn,
    CiInboxOut,
    CiIndent,
    CiInstagram,
    CiKeyboard,
    CiLaptop,
    CiLemon,
    CiLight,
    CiLineHeight,
    CiLink,
    CiLinkedin,
    CiLocationArrow1,
    CiLocationOff,
    CiLocationOn,
    CiLock,
    CiLogin,
    CiLogout,
    CiLollipop,
    CiMail,
    CiMap,
    CiMapPin,
    CiMaximize1,
    CiMaximize2,
    CiMedal,
    CiMedicalCase,
    CiMedicalClipboard,
    CiMedicalCross,
    CiMedicalMask,
    CiMemoPad,
    CiMenuBurger,
    CiMenuFries,
    CiMenuKebab,
    CiMicrochip,
    CiMicrophoneOff,
    CiMicrophoneOn,
    CiMinimize1,
    CiMinimize2,
    CiMobile1,
    CiMobile2,
    CiMobile3,
    CiMobile4,
    CiMoneyBill,
    CiMoneyCheck1,
    CiMonitor,
    CiMountain1,
    CiMug1,
    CiMusicNote1,
    CiNoWaitingSign,
    CiPalette,
    CiPaperplane,
    CiParking1,
    CiPassport1,
    CiPause1,
    CiPen,
    CiPenpot,
    CiPercent,
    CiPhone,
    CiPickerEmpty,
    CiPickerHalf,
    CiPill,
    CiPillsBottle1,
    CiPizza,
    CiPlane,
    CiPlay1,
    CiPlug1,
    CiPower,
    CiRainbow,
    CiRead,
    CiReceipt,
    CiRedo,
    CiRepeat,
    CiRollingSuitcase,
    CiRoute,
    CiRouter,
    CiRuler,
    CiSatellite1,
    CiSaveDown1,
    CiSaveDown2,
    CiSaveUp1,
    CiSaveUp2,
    CiSearch,
    CiServer,
    CiSettings,
    CiShare1,
    CiShare2,
    CiShirt,
    CiShop,
    CiShoppingBasket,
    CiShoppingCart,
    CiShoppingTag,
    CiShuffle,
    CiSignpostDuo1,
    CiSignpostL1,
    CiSignpostR1,
    CiSliderHorizontal,
    CiSliderVertical,
    CiSpeaker,
    CiSquareAlert,
    CiSquareCheck,
    CiSquareChevDown,
    CiSquareChevLeft,
    CiSquareChevRight,
    CiSquareChevUp,
    CiSquareInfo,
    CiSquareMinus,
    CiSquareMore,
    CiSquarePlus,
    CiSquareQuestion,
    CiSquareRemove,
    CiStar,
    CiStethoscope,
    CiStickyNote,
    CiStop1,
    CiStopSign1,
    CiStopwatch,
    CiStreamOff,
    CiStreamOn,
    CiSun,
    CiTablets1,
    CiTempHigh,
    CiText,
    CiTextAlignCenter,
    CiTextAlignJustify,
    CiTextAlignLeft,
    CiTextAlignRight,
    CiTimer,
    CiTrash,
    CiTrophy,
    CiTurnL1,
    CiTurnR1,
    CiTwitter,
    CiUmbrella,
    CiUndo,
    CiUnlock,
    CiUnread,
    CiUsb,
    CiUser,
    CiVault,
    CiVial,
    CiVideoOff,
    CiVideoOn,
    CiViewBoard,
    CiViewColumn,
    CiViewList,
    CiViewTable,
    CiViewTimeline,
    CiVirus,
    CiVoicemail,
    CiVolume,
    CiVolumeHigh,
    CiVolumeMute,
    CiWallet,
    CiWarning,
    CiWavePulse1,
    CiWheat,
    CiWifiOff,
    CiWifiOn,
    CiYoutube,
} from 'react-icons/ci'

export const colorIcon: Record<string, ReactNode> = {
    FcAcceptDatabase: <FcAcceptDatabase />,
    FcAbout: <FcAbout />,
    FcAddColumn: <FcAddColumn />,
    FcAddDatabase: <FcAddDatabase />,
    FcAddImage: <FcAddImage />,
    FcAddRow: <FcAddRow />,
    FcAddressBook: <FcAddressBook />,
    FcAdvance: <FcAdvance />,
    FcAdvertising: <FcAdvertising />,
    FcAlarmClock: <FcAlarmClock />,
    FcAlphabeticalSortingAz: <FcAlphabeticalSortingAz />,
    FcAlphabeticalSortingZa: <FcAlphabeticalSortingZa />,
    FcAndroidOs: <FcAndroidOs />,
    FcAnswers: <FcAnswers />,
    FcApproval: <FcApproval />,
    FcApprove: <FcApprove />,
    FcAreaChart: <FcAreaChart />,
    FcAssistant: <FcAssistant />,
    FcAudioFile: <FcAudioFile />,
    FcAutomatic: <FcAutomatic />,
    FcAutomotive: <FcAutomotive />,
    FcBadDecision: <FcBadDecision />,
    FcBarChart: <FcBarChart />,
    FcBbc: <FcBbc />,
    FcBearish: <FcBearish />,
    FcBinoculars: <FcBinoculars />,
    FcBiohazard: <FcBiohazard />,
    FcBiomass: <FcBiomass />,
    FcBiotech: <FcBiotech />,
    FcBookmark: <FcBookmark />,
    FcBriefcase: <FcBriefcase />,
    FcBrokenLink: <FcBrokenLink />,
    FcBullish: <FcBullish />,
    FcBusiness: <FcBusiness />,
    FcBusinessContact: <FcBusinessContact />,
    FcBusinessman: <FcBusinessman />,
    FcBusinesswoman: <FcBusinesswoman />,
    FcButtingIn: <FcButtingIn />,
    FcCableRelease: <FcCableRelease />,
    FcCalculator: <FcCalculator />,
    FcCalendar: <FcCalendar />,
    FcCallTransfer: <FcCallTransfer />,
    FcCallback: <FcCallback />,
    FcCamcorder: <FcCamcorder />,
    FcCamcorderPro: <FcCamcorderPro />,
    FcCamera: <FcCamera />,
    FcCameraAddon: <FcCameraAddon />,
    FcCameraIdentification: <FcCameraIdentification />,
    FcCancel: <FcCancel />,
    FcCandleSticks: <FcCandleSticks />,
    FcCapacitor: <FcCapacitor />,
    FcCdLogo: <FcCdLogo />,
    FcCellPhone: <FcCellPhone />,
    FcChargeBattery: <FcChargeBattery />,
    FcCheckmark: <FcCheckmark />,
    FcCircuit: <FcCircuit />,
    FcClapperboard: <FcClapperboard />,
    FcClearFilters: <FcClearFilters />,
    FcClock: <FcClock />,
    FcCloseUpMode: <FcCloseUpMode />,
    FcCloth: <FcCloth />,
    FcCollaboration: <FcCollaboration />,
    FcCollapse: <FcCollapse />,
    FcCollect: <FcCollect />,
    FcComboChart: <FcComboChart />,
    FcCommandLine: <FcCommandLine />,
    FcComments: <FcComments />,
    FcCompactCamera: <FcCompactCamera />,
    FcConferenceCall: <FcConferenceCall />,
    FcContacts: <FcContacts />,
    FcCopyleft: <FcCopyleft />,
    FcCopyright: <FcCopyright />,
    FcCrystalOscillator: <FcCrystalOscillator />,
    FcCurrencyExchange: <FcCurrencyExchange />,
    FcCursor: <FcCursor />,
    FcCustomerSupport: <FcCustomerSupport />,
    FcDam: <FcDam />,
    FcDataBackup: <FcDataBackup />,
    FcDataConfiguration: <FcDataConfiguration />,
    FcDataEncryption: <FcDataEncryption />,
    FcDataProtection: <FcDataProtection />,
    FcDataRecovery: <FcDataRecovery />,
    FcDataSheet: <FcDataSheet />,
    FcDatabase: <FcDatabase />,
    FcDebian: <FcDebian />,
    FcDebt: <FcDebt />,
    FcDecision: <FcDecision />,
    FcDeleteColumn: <FcDeleteColumn />,
    FcDeleteDatabase: <FcDeleteDatabase />,
    FcDeleteRow: <FcDeleteRow />,
    FcDepartment: <FcDepartment />,
    FcDeployment: <FcDeployment />,
    FcDiploma1: <FcDiploma1 />,
    FcDiploma2: <FcDiploma2 />,
    FcDisapprove: <FcDisapprove />,
    FcDisclaimer: <FcDisclaimer />,
    FcDislike: <FcDislike />,
    FcDisplay: <FcDisplay />,
    FcDoNotInhale: <FcDoNotInhale />,
    FcDoNotInsert: <FcDoNotInsert />,
    FcDoNotMix: <FcDoNotMix />,
    FcDocument: <FcDocument />,
    FcDonate: <FcDonate />,
    FcDoughnutChart: <FcDoughnutChart />,
    FcDown: <FcDown />,
    FcDownLeft: <FcDownLeft />,
    FcDownRight: <FcDownRight />,
    FcDownload: <FcDownload />,
    FcDribbble: <FcDribbble />,
    FcDvdLogo: <FcDvdLogo />,
    FcEditImage: <FcEditImage />,
    FcElectricalSensor: <FcElectricalSensor />,
    FcElectricalThreshold: <FcElectricalThreshold />,
    FcElectricity: <FcElectricity />,
    FcElectroDevices: <FcElectroDevices />,
    FcElectronics: <FcElectronics />,
    FcEmptyBattery: <FcEmptyBattery />,
    FcEmptyFilter: <FcEmptyFilter />,
    FcEmptyTrash: <FcEmptyTrash />,
    FcEndCall: <FcEndCall />,
    FcEngineering: <FcEngineering />,
    FcEnteringHeavenAlive: <FcEnteringHeavenAlive />,
    FcExpand: <FcExpand />,
    FcExpired: <FcExpired />,
    FcExport: <FcExport />,
    FcExternal: <FcExternal />,
    FcFactory: <FcFactory />,
    FcFactoryBreakdown: <FcFactoryBreakdown />,
    FcFaq: <FcFaq />,
    FcFeedIn: <FcFeedIn />,
    FcFeedback: <FcFeedback />,
    FcFile: <FcFile />,
    FcFilingCabinet: <FcFilingCabinet />,
    FcFilledFilter: <FcFilledFilter />,
    FcFilm: <FcFilm />,
    FcFilmReel: <FcFilmReel />,
    FcFinePrint: <FcFinePrint />,
    FcFlashAuto: <FcFlashAuto />,
    FcFlashOff: <FcFlashOff />,
    FcFlashOn: <FcFlashOn />,
    FcFlowChart: <FcFlowChart />,
    FcFolder: <FcFolder />,
    FcFrame: <FcFrame />,
    FcFullBattery: <FcFullBattery />,
    FcFullTrash: <FcFullTrash />,
    FcGallery: <FcGallery />,
    FcGenealogy: <FcGenealogy />,
    FcGenericSortingAsc: <FcGenericSortingAsc />,
    FcGenericSortingDesc: <FcGenericSortingDesc />,
    FcGlobe: <FcGlobe />,
    FcGoodDecision: <FcGoodDecision />,
    FcGoogle: <FcGoogle />,
    FcGraduationCap: <FcGraduationCap />,
    FcGrid: <FcGrid />,
    FcHeadset: <FcHeadset />,
    FcHeatMap: <FcHeatMap />,
    FcHighBattery: <FcHighBattery />,
    FcHighPriority: <FcHighPriority />,
    FcHome: <FcHome />,
    FcIcons8Cup: <FcIcons8Cup />,
    FcIdea: <FcIdea />,
    FcImageFile: <FcImageFile />,
    FcImport: <FcImport />,
    FcInTransit: <FcInTransit />,
    FcInfo: <FcInfo />,
    FcInspection: <FcInspection />,
    FcIntegratedWebcam: <FcIntegratedWebcam />,
    FcInternal: <FcInternal />,
    FcInvite: <FcInvite />,
    FcIpad: <FcIpad />,
    FcIphone: <FcIphone />,
    FcKey: <FcKey />,
    FcKindle: <FcKindle />,
    FcLandscape: <FcLandscape />,
    FcLeave: <FcLeave />,
    FcLeft: <FcLeft />,
    FcLeftDown: <FcLeftDown />,
    FcLeftDown2: <FcLeftDown2 />,
    FcLeftUp: <FcLeftUp />,
    FcLeftUp2: <FcLeftUp2 />,
    FcLibrary: <FcLibrary />,
    FcLightAtTheEndOfTunnel: <FcLightAtTheEndOfTunnel />,
    FcLike: <FcLike />,
    FcLikePlaceholder: <FcLikePlaceholder />,
    FcLineChart: <FcLineChart />,
    FcLink: <FcLink />,
    FcLinux: <FcLinux />,
    FcList: <FcList />,
    FcLock: <FcLock />,
    FcLockLandscape: <FcLockLandscape />,
    FcLockPortrait: <FcLockPortrait />,
    FcLowBattery: <FcLowBattery />,
    FcLowPriority: <FcLowPriority />,
    FcMakeDecision: <FcMakeDecision />,
    FcManager: <FcManager />,
    FcMediumPriority: <FcMediumPriority />,
    FcMenu: <FcMenu />,
    FcMindMap: <FcMindMap />,
    FcMinus: <FcMinus />,
    FcMissedCall: <FcMissedCall />,
    FcMms: <FcMms />,
    FcMoneyTransfer: <FcMoneyTransfer />,
    FcMultipleCameras: <FcMultipleCameras />,
    FcMultipleDevices: <FcMultipleDevices />,
    FcMultipleInputs: <FcMultipleInputs />,
    FcMultipleSmartphones: <FcMultipleSmartphones />,
    FcMusic: <FcMusic />,
    FcNegativeDynamic: <FcNegativeDynamic />,
    FcNeutralDecision: <FcNeutralDecision />,
    FcNeutralTrading: <FcNeutralTrading />,
    FcNews: <FcNews />,
    FcNext: <FcNext />,
    FcNfcSign: <FcNfcSign />,
    FcNightLandscape: <FcNightLandscape />,
    FcNightPortrait: <FcNightPortrait />,
    FcNoIdea: <FcNoIdea />,
    FcNoVideo: <FcNoVideo />,
    FcNook: <FcNook />,
    FcNumericalSorting12: <FcNumericalSorting12 />,
    FcNumericalSorting21: <FcNumericalSorting21 />,
    FcOk: <FcOk />,
    FcOldTimeCamera: <FcOldTimeCamera />,
    FcOnlineSupport: <FcOnlineSupport />,
    FcOpenedFolder: <FcOpenedFolder />,
    FcOrgUnit: <FcOrgUnit />,
    FcOrganization: <FcOrganization />,
    FcOvertime: <FcOvertime />,
    FcPackage: <FcPackage />,
    FcPaid: <FcPaid />,
    FcPanorama: <FcPanorama />,
    FcParallelTasks: <FcParallelTasks />,
    FcPhone: <FcPhone />,
    FcPhoneAndroid: <FcPhoneAndroid />,
    FcPhotoReel: <FcPhotoReel />,
    FcPicture: <FcPicture />,
    FcPieChart: <FcPieChart />,
    FcPlanner: <FcPlanner />,
    FcPlus: <FcPlus />,
    FcPodiumWithAudience: <FcPodiumWithAudience />,
    FcPodiumWithSpeaker: <FcPodiumWithSpeaker />,
    FcPodiumWithoutSpeaker: <FcPodiumWithoutSpeaker />,
    FcPortraitMode: <FcPortraitMode />,
    FcPositiveDynamic: <FcPositiveDynamic />,
    FcPrevious: <FcPrevious />,
    FcPrint: <FcPrint />,
    FcPrivacy: <FcPrivacy />,
    FcProcess: <FcProcess />,
    FcPuzzle: <FcPuzzle />,
    FcQuestions: <FcQuestions />,
    FcRadarPlot: <FcRadarPlot />,
    FcRating: <FcRating />,
    FcRatings: <FcRatings />,
    FcReading: <FcReading />,
    FcReadingEbook: <FcReadingEbook />,
    FcReddit: <FcReddit />,
    FcRedo: <FcRedo />,
    FcRefresh: <FcRefresh />,
    FcRegisteredTrademark: <FcRegisteredTrademark />,
    FcRemoveImage: <FcRemoveImage />,
    FcReuse: <FcReuse />,
    FcRight: <FcRight />,
    FcRightDown: <FcRightDown />,
    FcRightDown2: <FcRightDown2 />,
    FcRightUp: <FcRightUp />,
    FcRightUp2: <FcRightUp2 />,
    FcRotateCamera: <FcRotateCamera />,
    FcRotateToLandscape: <FcRotateToLandscape />,
    FcRotateToPortrait: <FcRotateToPortrait />,
    FcRuler: <FcRuler />,
    FcRules: <FcRules />,
    FcSafe: <FcSafe />,
    FcSalesPerformance: <FcSalesPerformance />,
    FcScatterPlot: <FcScatterPlot />,
    FcSearch: <FcSearch />,
    FcSelfServiceKiosk: <FcSelfServiceKiosk />,
    FcSelfie: <FcSelfie />,
    FcSerialTasks: <FcSerialTasks />,
    FcServiceMark: <FcServiceMark />,
    FcServices: <FcServices />,
    FcSettings: <FcSettings />,
    FcShare: <FcShare />,
    FcShipped: <FcShipped />,
    FcShop: <FcShop />,
    FcSignature: <FcSignature />,
    FcSimCard: <FcSimCard />,
    FcSimCardChip: <FcSimCardChip />,
    FcSlrBackSide: <FcSlrBackSide />,
    FcSmartphoneTablet: <FcSmartphoneTablet />,
    FcSms: <FcSms />,
    FcSoundRecordingCopyright: <FcSoundRecordingCopyright />,
    FcSpeaker: <FcSpeaker />,
    FcSportsMode: <FcSportsMode />,
    FcStackOfPhotos: <FcStackOfPhotos />,
    FcStart: <FcStart />,
    FcStatistics: <FcStatistics />,
    FcSteam: <FcSteam />,
    FcStumbleupon: <FcStumbleupon />,
    FcSupport: <FcSupport />,
    FcSurvey: <FcSurvey />,
    FcSwitchCamera: <FcSwitchCamera />,
    FcSynchronize: <FcSynchronize />,
    FcTabletAndroid: <FcTabletAndroid />,
    FcTemplate: <FcTemplate />,
    FcTimeline: <FcTimeline />,
    FcTodoList: <FcTodoList />,
    FcTouchscreenSmartphone: <FcTouchscreenSmartphone />,
    FcTrademark: <FcTrademark />,
    FcTreeStructure: <FcTreeStructure />,
    FcTwoSmartphones: <FcTwoSmartphones />,
    FcUndo: <FcUndo />,
    FcUnlock: <FcUnlock />,
    FcUp: <FcUp />,
    FcUpLeft: <FcUpLeft />,
    FcUpRight: <FcUpRight />,
    FcUpload: <FcUpload />,
    FcUsb: <FcUsb />,
    FcVideoCall: <FcVideoCall />,
    FcVideoFile: <FcVideoFile />,
    FcVideoProjector: <FcVideoProjector />,
    FcViewDetails: <FcViewDetails />,
    FcVip: <FcVip />,
    FcVlc: <FcVlc />,
    FcVoicePresentation: <FcVoicePresentation />,
    FcVoicemail: <FcVoicemail />,
    FcWebcam: <FcWebcam />,
    FcWiFiLogo: <FcWiFiLogo />,
    FcWikipedia: <FcWikipedia />,
    FcWorkflow: <FcWorkflow />,
}

export const circumIcons: Record<string, ReactNode> = {
    CiAirportSign1: <CiAirportSign1 />,
    CiAlarmOff: <CiAlarmOff />,
    CiAlarmOn: <CiAlarmOn />,
    CiAlignBottom: <CiAlignBottom />,
    CiAlignCenterH: <CiAlignCenterH />,
    CiAlignCenterV: <CiAlignCenterV />,
    CiAlignLeft: <CiAlignLeft />,
    CiAlignRight: <CiAlignRight />,
    CiAlignTop: <CiAlignTop />,
    CiApple: <CiApple />,
    CiAt: <CiAt />,
    CiAvocado: <CiAvocado />,
    CiBacon: <CiBacon />,
    CiBadgeDollar: <CiBadgeDollar />,
    CiBag1: <CiBag1 />,
    CiBandage: <CiBandage />,
    CiBank: <CiBank />,
    CiBarcode: <CiBarcode />,
    CiBaseball: <CiBaseball />,
    CiBasketball: <CiBasketball />,
    CiBatteryCharging: <CiBatteryCharging />,
    CiBatteryEmpty: <CiBatteryEmpty />,
    CiBatteryFull: <CiBatteryFull />,
    CiBeaker1: <CiBeaker1 />,
    CiBeerMugFull: <CiBeerMugFull />,
    CiBellOff: <CiBellOff />,
    CiBellOn: <CiBellOn />,
    CiBezier: <CiBezier />,
    CiBitcoin: <CiBitcoin />,
    CiBluetooth: <CiBluetooth />,
    CiBookmark: <CiBookmark />,
    CiBookmarkCheck: <CiBookmarkCheck />,
    CiBookmarkMinus: <CiBookmarkMinus />,
    CiBookmarkPlus: <CiBookmarkPlus />,
    CiBookmarkRemove: <CiBookmarkRemove />,
    CiBowlNoodles: <CiBowlNoodles />,
    CiBoxList: <CiBoxList />,
    CiBoxes: <CiBoxes />,
    CiBrightnessDown: <CiBrightnessDown />,
    CiBrightnessUp: <CiBrightnessUp />,
    CiBullhorn: <CiBullhorn />,
    CiBurger: <CiBurger />,
    CiCalculator1: <CiCalculator1 />,
    CiCalculator2: <CiCalculator2 />,
    CiCalendar: <CiCalendar />,
    CiCalendarDate: <CiCalendarDate />,
    CiCamera: <CiCamera />,
    CiChat1: <CiChat1 />,
    CiChat2: <CiChat2 />,
    CiCircleAlert: <CiCircleAlert />,
    CiCircleCheck: <CiCircleCheck />,
    CiCircleChevDown: <CiCircleChevDown />,
    CiCircleChevLeft: <CiCircleChevLeft />,
    CiCircleChevRight: <CiCircleChevRight />,
    CiCircleChevUp: <CiCircleChevUp />,
    CiCircleInfo: <CiCircleInfo />,
    CiCircleList: <CiCircleList />,
    CiCircleMinus: <CiCircleMinus />,
    CiCircleMore: <CiCircleMore />,
    CiCirclePlus: <CiCirclePlus />,
    CiCircleQuestion: <CiCircleQuestion />,
    CiCircleRemove: <CiCircleRemove />,
    CiClock1: <CiClock1 />,
    CiClock2: <CiClock2 />,
    CiCloud: <CiCloud />,
    CiCloudDrizzle: <CiCloudDrizzle />,
    CiCloudMoon: <CiCloudMoon />,
    CiCloudOff: <CiCloudOff />,
    CiCloudOn: <CiCloudOn />,
    CiCloudRainbow: <CiCloudRainbow />,
    CiCloudSun: <CiCloudSun />,
    CiCoffeeBean: <CiCoffeeBean />,
    CiCoffeeCup: <CiCoffeeCup />,
    CiCoinInsert: <CiCoinInsert />,
    CiCoins1: <CiCoins1 />,
    CiCompass1: <CiCompass1 />,
    CiCreditCard1: <CiCreditCard1 />,
    CiCreditCard2: <CiCreditCard2 />,
    CiCreditCardOff: <CiCreditCardOff />,
    CiCrop: <CiCrop />,
    CiDark: <CiDark />,
    CiDatabase: <CiDatabase />,
    CiDeliveryTruck: <CiDeliveryTruck />,
    CiDesktop: <CiDesktop />,
    CiDesktopMouse1: <CiDesktopMouse1 />,
    CiDesktopMouse2: <CiDesktopMouse2 />,
    CiDiscount1: <CiDiscount1 />,
    CiDollar: <CiDollar />,
    CiDroplet: <CiDroplet />,
    CiDumbbell: <CiDumbbell />,
    CiEdit: <CiEdit />,
    CiEraser: <CiEraser />,
    CiExport: <CiExport />,
    CiFaceFrown: <CiFaceFrown />,
    CiFaceMeh: <CiFaceMeh />,
    CiFaceSmile: <CiFaceSmile />,
    CiFacebook: <CiFacebook />,
    CiFileOff: <CiFileOff />,
    CiFileOn: <CiFileOn />,
    CiFilter: <CiFilter />,
    CiFlag1: <CiFlag1 />,
    CiFloppyDisk: <CiFloppyDisk />,
    CiFolderOff: <CiFolderOff />,
    CiFolderOn: <CiFolderOn />,
    CiFootball: <CiFootball />,
    CiForkAndKnife: <CiForkAndKnife />,
    CiFries: <CiFries />,
    CiGift: <CiGift />,
    CiGlass: <CiGlass />,
    CiGlobe: <CiGlobe />,
    CiGps: <CiGps />,
    CiGrid2H: <CiGrid2H />,
    CiGrid2V: <CiGrid2V />,
    CiGrid31: <CiGrid31 />,
    CiGrid32: <CiGrid32 />,
    CiGrid41: <CiGrid41 />,
    CiGrid42: <CiGrid42 />,
    CiHardDrive: <CiHardDrive />,
    CiHashtag: <CiHashtag />,
    CiHeadphones: <CiHeadphones />,
    CiHeart: <CiHeart />,
    CiHome: <CiHome />,
    CiHospital1: <CiHospital1 />,
    CiHotdog: <CiHotdog />,
    CiIceCream: <CiIceCream />,
    CiImageOff: <CiImageOff />,
    CiImageOn: <CiImageOn />,
    CiImport: <CiImport />,
    CiInboxIn: <CiInboxIn />,
    CiInboxOut: <CiInboxOut />,
    CiIndent: <CiIndent />,
    CiInstagram: <CiInstagram />,
    CiKeyboard: <CiKeyboard />,
    CiLaptop: <CiLaptop />,
    CiLemon: <CiLemon />,
    CiLight: <CiLight />,
    CiLineHeight: <CiLineHeight />,
    CiLink: <CiLink />,
    CiLinkedin: <CiLinkedin />,
    CiLocationArrow1: <CiLocationArrow1 />,
    CiLocationOff: <CiLocationOff />,
    CiLocationOn: <CiLocationOn />,
    CiLock: <CiLock />,
    CiLogin: <CiLogin />,
    CiLogout: <CiLogout />,
    CiLollipop: <CiLollipop />,
    CiMail: <CiMail />,
    CiMap: <CiMap />,
    CiMapPin: <CiMapPin />,
    CiMaximize1: <CiMaximize1 />,
    CiMaximize2: <CiMaximize2 />,
    CiMedal: <CiMedal />,
    CiMedicalCase: <CiMedicalCase />,
    CiMedicalClipboard: <CiMedicalClipboard />,
    CiMedicalCross: <CiMedicalCross />,
    CiMedicalMask: <CiMedicalMask />,
    CiMemoPad: <CiMemoPad />,
    CiMenuBurger: <CiMenuBurger />,
    CiMenuFries: <CiMenuFries />,
    CiMenuKebab: <CiMenuKebab />,
    CiMicrochip: <CiMicrochip />,
    CiMicrophoneOff: <CiMicrophoneOff />,
    CiMicrophoneOn: <CiMicrophoneOn />,
    CiMinimize1: <CiMinimize1 />,
    CiMinimize2: <CiMinimize2 />,
    CiMobile1: <CiMobile1 />,
    CiMobile2: <CiMobile2 />,
    CiMobile3: <CiMobile3 />,
    CiMobile4: <CiMobile4 />,
    CiMoneyBill: <CiMoneyBill />,
    CiMoneyCheck1: <CiMoneyCheck1 />,
    CiMonitor: <CiMonitor />,
    CiMountain1: <CiMountain1 />,
    CiMug1: <CiMug1 />,
    CiMusicNote1: <CiMusicNote1 />,
    CiNoWaitingSign: <CiNoWaitingSign />,
    CiPalette: <CiPalette />,
    CiPaperplane: <CiPaperplane />,
    CiParking1: <CiParking1 />,
    CiPassport1: <CiPassport1 />,
    CiPause1: <CiPause1 />,
    CiPen: <CiPen />,
    CiPenpot: <CiPenpot />,
    CiPercent: <CiPercent />,
    CiPhone: <CiPhone />,
    CiPickerEmpty: <CiPickerEmpty />,
    CiPickerHalf: <CiPickerHalf />,
    CiPill: <CiPill />,
    CiPillsBottle1: <CiPillsBottle1 />,
    CiPizza: <CiPizza />,
    CiPlane: <CiPlane />,
    CiPlay1: <CiPlay1 />,
    CiPlug1: <CiPlug1 />,
    CiPower: <CiPower />,
    CiRainbow: <CiRainbow />,
    CiRead: <CiRead />,
    CiReceipt: <CiReceipt />,
    CiRedo: <CiRedo />,
    CiRepeat: <CiRepeat />,
    CiRollingSuitcase: <CiRollingSuitcase />,
    CiRoute: <CiRoute />,
    CiRouter: <CiRouter />,
    CiRuler: <CiRuler />,
    CiSatellite1: <CiSatellite1 />,
    CiSaveDown1: <CiSaveDown1 />,
    CiSaveDown2: <CiSaveDown2 />,
    CiSaveUp1: <CiSaveUp1 />,
    CiSaveUp2: <CiSaveUp2 />,
    CiSearch: <CiSearch />,
    CiServer: <CiServer />,
    CiSettings: <CiSettings />,
    CiShare1: <CiShare1 />,
    CiShare2: <CiShare2 />,
    CiShirt: <CiShirt />,
    CiShop: <CiShop />,
    CiShoppingBasket: <CiShoppingBasket />,
    CiShoppingCart: <CiShoppingCart />,
    CiShoppingTag: <CiShoppingTag />,
    CiShuffle: <CiShuffle />,
    CiSignpostDuo1: <CiSignpostDuo1 />,
    CiSignpostL1: <CiSignpostL1 />,
    CiSignpostR1: <CiSignpostR1 />,
    CiSliderHorizontal: <CiSliderHorizontal />,
    CiSliderVertical: <CiSliderVertical />,
    CiSpeaker: <CiSpeaker />,
    CiSquareAlert: <CiSquareAlert />,
    CiSquareCheck: <CiSquareCheck />,
    CiSquareChevDown: <CiSquareChevDown />,
    CiSquareChevLeft: <CiSquareChevLeft />,
    CiSquareChevRight: <CiSquareChevRight />,
    CiSquareChevUp: <CiSquareChevUp />,
    CiSquareInfo: <CiSquareInfo />,
    CiSquareMinus: <CiSquareMinus />,
    CiSquareMore: <CiSquareMore />,
    CiSquarePlus: <CiSquarePlus />,
    CiSquareQuestion: <CiSquareQuestion />,
    CiSquareRemove: <CiSquareRemove />,
    CiStar: <CiStar />,
    CiStethoscope: <CiStethoscope />,
    CiStickyNote: <CiStickyNote />,
    CiStop1: <CiStop1 />,
    CiStopSign1: <CiStopSign1 />,
    CiStopwatch: <CiStopwatch />,
    CiStreamOff: <CiStreamOff />,
    CiStreamOn: <CiStreamOn />,
    CiSun: <CiSun />,
    CiTablets1: <CiTablets1 />,
    CiTempHigh: <CiTempHigh />,
    CiText: <CiText />,
    CiTextAlignCenter: <CiTextAlignCenter />,
    CiTextAlignJustify: <CiTextAlignJustify />,
    CiTextAlignLeft: <CiTextAlignLeft />,
    CiTextAlignRight: <CiTextAlignRight />,
    CiTimer: <CiTimer />,
    CiTrash: <CiTrash />,
    CiTrophy: <CiTrophy />,
    CiTurnL1: <CiTurnL1 />,
    CiTurnR1: <CiTurnR1 />,
    CiTwitter: <CiTwitter />,
    CiUmbrella: <CiUmbrella />,
    CiUndo: <CiUndo />,
    CiUnlock: <CiUnlock />,
    CiUnread: <CiUnread />,
    CiUsb: <CiUsb />,
    CiUser: <CiUser />,
    CiVault: <CiVault />,
    CiVial: <CiVial />,
    CiVideoOff: <CiVideoOff />,
    CiVideoOn: <CiVideoOn />,
    CiViewBoard: <CiViewBoard />,
    CiViewColumn: <CiViewColumn />,
    CiViewList: <CiViewList />,
    CiViewTable: <CiViewTable />,
    CiViewTimeline: <CiViewTimeline />,
    CiVirus: <CiVirus />,
    CiVoicemail: <CiVoicemail />,
    CiVolume: <CiVolume />,
    CiVolumeHigh: <CiVolumeHigh />,
    CiVolumeMute: <CiVolumeMute />,
    CiWallet: <CiWallet />,
    CiWarning: <CiWarning />,
    CiWavePulse1: <CiWavePulse1 />,
    CiWheat: <CiWheat />,
    CiWifiOff: <CiWifiOff />,
    CiWifiOn: <CiWifiOn />,
    CiYoutube: <CiYoutube />,
}
