import React from 'react'

import NavigationSidebar from '@/components/navigation/navigation-sidebar'
import { ModalProvider } from '@/components/provider/ModalProvider'
import { bitter } from '@/lib/font'
import ReduxProvider from '@/redux/redux-provider'
import type { Metadata } from 'next'
import './globals.css'
import './main.scss'

export const metadata: Metadata = {
    title: 'Resume Builder',
    description: 'Generated by next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={` ${bitter.className}  `}>
                <ReduxProvider>
                    <div className="h-full">
                        <div className="hidden md:!flex h-full w-[72px] z-30 flex-col fixed inset-y-0">
                            <NavigationSidebar />
                        </div>

                        <main className="md:pl-[72px] h-full">{children}</main>
                    </div>
                    <ModalProvider />
                </ReduxProvider>
            </body>
        </html>
    )
}
