import React from 'react'

import { ModalProvider } from '@/components/provider/modal-provider'
import ReduxProvider from '@/redux/redux-provider'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import './main.scss'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <ReduxProvider>
                    {children}
                    <ModalProvider />
                </ReduxProvider>
            </body>
        </html>
    )
}
